# user postgres for everything
#
development:
  adapter: postgresql
  database: fire_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: fire_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fire_production
  pool: 5
  timeout: 5000

